name: Update Activity Graph
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          USERNAME: ForgeAndFangStudio
          COMMIT_MESSAGE: "chore: update activity graph"
