name: Metrics
on:
  schedule: [{ cron: "0 7 * * *" }]  # daily 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) CHECKOUT FIRST so the workspace is the repo
      - uses: actions/checkout@v4

      # 2) Generate light card into the repo path
      - name: Metrics (light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # classic PAT: read:user, repo, notifications
          user: ForgeAndFangStudio
          template: classic
          filename: assets/metrics-light.svg
          config_timezone: Africa/Johannesburg
          config_animations: yes
          config_background: transparent
          base: header, repositories, activity, community, metadata
          plugin_languages: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_reactions: yes
          plugin_calendar: yes
          plugin_traffic: yes

      # 3) Generate dark card into the repo path
      - name: Metrics (dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ForgeAndFangStudio
          template: classic
          filename: assets/metrics-dark.svg
          config_timezone: Africa/Johannesburg
          config_animations: yes
          config_background: "#0d1117"
          base: header, repositories, activity, community, metadata
          plugin_languages: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_reactions: yes
          plugin_calendar: yes
          plugin_traffic: yes

      # 4) Commit both files
      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/metrics-*.svg || echo "No SVG files found"
          
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: update metrics (light/dark)"
            
            # Pull with rebase to get any new remote commits
            git pull --rebase origin main
            
            # Push with retry logic
            for i in 1 2 3; do
              if git push origin main; then
                echo "Successfully pushed on attempt $i"
                break
              else
                echo "Push failed, retrying ($i/3)..."
                git pull --rebase origin main
                sleep 2
              fi
            done
          else
            echo "No changes to commit"
          fi
